[package]
name = "marshal-secrets"
description = "Secret sources, boundary injection and redaction"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
marshal-core.workspace = true
marshal-config.workspace = true
marshal-policy.workspace = true
marshal-http.workspace = true
http.workspace = true
bytes.workspace = true
serde_json.workspace = true
async-trait.workspace = true
tokio.workspace = true
rustls.workspace = true
thiserror.workspace = true
tracing.workspace = true
sha2.workspace = true
getrandom.workspace = true
ring.workspace = true
rustls-pemfile.workspace = true
hmac.workspace = true
time.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
rcgen.workspace = true
